# Generated by Django 3.1 on 2020-08-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
