# Generated by Django 3.1 on 2020-08-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
