# Generated by Django 3.1 on 2020-08-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='colors',
            field=models.CharField(choices=[('RD', 'Red'), ('GR', 'Green'), ('BL', 'Blue')], default='BL', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
