# Generated by Django 3.1 on 2020-08-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200828_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.desk')),
            ],
        ),
    ]
