# Generated by Django 3.1 on 2020-08-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Task',
            new_name='task',
        ),
    ]
